version: "3.0"

services:
  database:
    image: postgres:14.5-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-organize}
      POSTGRES_USER: ${POSTGRES_USER:-organize_usr}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
